{{- if .Values.enableExternalMetricsApi }}
{{- if .Capabilities.APIVersions.Has "apiregistration.k8s.io/v1" }}
apiVersion: apiregistration.k8s.io/v1
{{- else }}
apiVersion: apiregistration.k8s.io/v1beta1
{{- end }}
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
  labels:
    app: {{ template "kube-metrics-adapter.name" . }}
    chart: {{ template "kube-metrics-adapter.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  service:
    name: {{ template "kube-metrics-adapter.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: {{ if .Values.tls.enable }}false{{ else }}true{{ end }}
  groupPriorityMinimum: 100
  versionPriority: 100
{{- end}}
