---
- name: Load Balancer
  hosts: loadbalancers
  become: yes
  tasks:
  - name: Install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes
- name: Kubernetes
  hosts: kubernetes
  become: yes
  tasks:
  - name: Download K3s
    ansible.builtin.get_url:
      url: "https://github.com/k3s-io/k3s/releases/download/v1.29.3%2Bk3s1/k3s"
      dest: "/usr/local/bin/k3s"
      mode: "0755"
  - name: Install K3s service
    copy:
      src: files/systemd/k3s.service
      dest: /etc/systemd/system/k3s.service
      owner: root
      group: root
      mode: "0755"
  - name: Launch K3s service
    systemd:
      name: k3s.service
      enabled: true
      state: started
      daemon_reload: true
  - name: Fetch Kube config
    fetch:
      src: /etc/rancher/k3s/k3s.yaml
      dest: k3s.yaml
  - name: Insert current host
    replace:
      path: k3s.yaml
      regexp: "127\.0\.0\.1"
      replace: inventory_hostname
